### ISSUE TITLE
fs.js:844   return binding.stat(pathModule._makeLong(path));

### ISSUE THREAD

**Issue by hitfzyangdianshi** [cyberfoxmeow/makerboard#1]
```
qwertyu@ubuntu:~/makerboard$ sudo makerboard create my7688
fs.js:844
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat '/usr/local/lib/node_modules/makerboard/data'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/makerboard/lib/downloader.js:31:18)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:414:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at TLSSocket.socketOnData (_http_client.js:304:20)
    at emitOne (events.js:77:13)
```

**Comment by hitfzyangdianshi** [comment]
`qwertyu@ubuntu:/usr/local/lib/node_modules/makerboard$ sudo mkdir data`

**Comment by hitfzyangdianshi** [comment]
https://github.com/cfsghost/makerboard/issues/4#issuecomment-580387780
